### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by zkareemz** [unDemian/clipboard-history#13] opened 2015-03-02 07:29 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [clipboard-history](https://github.com/unDemian/clipboard-history) package, v0.6.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/user/.atom/packages/clipboard-history/lib/clipboard-history-view.coffee:103

TypeError: undefined is not a function
  at ClipboardHistoryView.module.exports.ClipboardHistoryView.confirmed (/Users/user/.atom/packages/clipboard-history/lib/clipboard-history-view.coffee:103:22)
  at ClipboardHistoryView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
  2x -0:50.9 core:move-right (atom-text-editor.editor.mini)
  3x -0:50.1 core:backspace (atom-text-editor.editor.mini)
     -0:49.4 core:confirm (atom-text-editor.editor.mini)
     -0:44.6 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:17.5 editor:select-to-first-character-of-line (atom-text-editor.editor)
     -0:12.9 core:backspace (atom-text-editor.editor)
     -0:12.1 editor:select-to-first-character-of-line (atom-text-editor.editor)
  2x -0:11.2 core:backspace (atom-text-editor.editor)
     -0:10.0 editor:select-to-first-character-of-line (atom-text-editor.editor)
     -0:09.3 core:backspace (atom-text-editor.editor)
     -0:06.4 clipboard-history:paste (atom-text-editor.editor)
  2x -0:05.4 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.7 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:04.4 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "coffee-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.3.3
atom-beautify, v0.21.3
atom-handlebars, v0.4.0
autocomplete-plus, v2.3.0
clipboard-history, v0.6.3
editorconfig, v0.3.0
file-icons, v1.5.0
fonts, v0.4.0
javascript-snippets, v1.0.0
minimap, v4.3.1
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by glorieux** [comment] 2015-03-02 14:28
Same here.

**Comment by unDemian** [comment] 2015-03-12 18:04
This is strange because I cannot replicate it on my windows or mac machine.

**Comment by unDemian** [comment] 2015-03-15 13:24
Are you guys still encountering this issue?

**Comment by davidmoret** [comment] 2015-03-16 14:42
Je viens d'installer le paquet et j'ai le même problème. Voulez-vous que je vous envoi le rapport d'erreur ?

**Comment by davidmoret** [comment] 2015-03-16 14:42
I just installed the package and I have the same problem. Do you want that I send you the error report?

**Comment by unDemian** [comment] 2015-03-16 22:10
It would be very helpful, thanks

**Comment by davidmoret** [comment] 2015-03-16 23:17
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [clipboard-history](https://github.com/unDemian/clipboard-history) package, v0.6.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/david/.atom/packages/clipboard-history/lib/clipboard-history-view.coffee:103

TypeError: undefined is not a function
  at ClipboardHistoryView.module.exports.ClipboardHistoryView.confirmed (/home/david/.atom/packages/clipboard-history/lib/clipboard-history-view.coffee:103:22)
  at ClipboardHistoryView.module.exports.SelectListView.confirmSelection (/home/david/.atom/packages/clipboard-history/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/home/david/.atom/packages/clipboard-history/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLOListElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -0:21.1 clipboard-history:paste (atom-text-editor.editor)
  4x -0:12.2 clipboard-history:copy (atom-text-editor.editor)
     -0:03.5 clipboard-history:paste (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "meteor-api",
      "atom-css-comb",
      "file-icons"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
clipboard-history, v0.6.3
color-picker, v1.4.4
emmet, v2.3.4
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
linter, v0.12.0
linter-csslint, v0.0.11
minimap, v4.3.1
monokai, v0.12.0
open-last-project, v0.3.4
project-manager, v1.15.5
seti-ui, v0.6.3
sync-settings, v0.2.2
tab-smart-sort, v0.1.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by davidmoret** [comment] 2015-03-17 11:05
I do not know if it helps but I noticed something. When the history window opens and I click, I have the error that appears but the item on which I clicked is in the clipboard. So it works but there is always this error notification.

**Comment by unDemian** [comment] 2015-03-17 21:09
This is fixed now. Thanks guys

**Closed by unDemian** 2015-03-17 21:09 UTC
